### ISSUE TITLE
Showcase Edit and Delete features as well

### ISSUE THREAD

**Issue by useEffects** [tecklens/shadcn-comments#2]
Hey! I have tried your package, unfortunately couldnt see how to use the edit and delete features. It would be greatly helpful if you can showcase it in the readme section as well!

**Comment by dieptv1999** [comment]
Thanks for feedback, i will update soon

**Comment by dieptv1999** [comment]
![Screenshot from 2024-10-23 23-55-31](https://github.com/user-attachments/assets/19276503-b8a7-4555-9b76-679a2ea41ffd)

New Feature: v1.0.3
